### ISSUE TITLE
Could not bind as LDAP admin

### ISSUE THREAD

**Issue by denbekker** [piwik/plugin-LoginLdap#115]
Hello, Im am trying to use the loginldap plugin in piwik. I entered all the information, I can connect and use the LDAP with username and password in other tools (ldapsearch / Apache Directory). When I use that in Piwik I am getting these errors:

DEBUG Login[2015-09-15 06:16:38] [3e29b] SessionInitializer::doAuthenticateSession: token_auth secret for $USERNAME not available before user is authenticated.
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] Auth\Base::tryFallbackAuth: trying normal auth with user password
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] Auth\Base::tryFallbackAuth: normal auth returned result code 0 for user '$USERNAME'
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] Model\LdapUsers: start authenticate() with [array]
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] Calling ldap_connect('$LDAPSERVER', 636)
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] ldap_connect result is [resource]
WARNING LoginLdap[2015-09-15 06:16:38] [3e29b] /data/www/piwik/htdocs/plugins/LoginLdap/Ldap/Client.php(91): Warning - ldap_bind(): Unable to bind to server: Can't contact LDAP server - Piwik 2.14.3 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] anonymous ldap_bind call finished; connection ok
INFO LoginLdap[2015-09-15 06:16:38] [3e29b] LdapUsers::makeLdapClient: Using LDAP server $LDAPSERVER:636
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] Model\LdapUsers: start getUser() with [array]
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] Calling ldap_bind([resource], '$LDAP_RESOURCE', <password[length=8]>)
WARNING LoginLdap[2015-09-15 06:16:38] [3e29b] /data/www/piwik/htdocs/plugins/LoginLdap/Ldap/Client.php(146): Warning - ldap_bind(): Unable to bind to server: Can't contact LDAP server - Piwik 2.14.3 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] ldap_bind result is '0'
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] Calling ldap_close([resource])
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] ldap_close returned true
DEBUG LoginLdap[2015-09-15 06:16:38] [3e29b] /data/www/piwik/htdocs/plugins/LoginLdap/Model/LdapUsers.php(592): Could not bind as LDAP admin.
  #0 /data/www/piwik/htdocs/plugins/LoginLdap/Model/LdapUsers.php(233): Piwik\Plugins\LoginLdap\Model\LdapUsers->bindAsAdmin(Object(Piwik\Plugins\LoginLdap\Ldap\Client), Object(Piwik\Plugins\LoginLdap\Ldap\ServerInfo))
  #1 /data/www/piwik/htdocs/plugins/LoginLdap/Model/LdapUsers.php(506): Piwik\Plugins\LoginLdap\Model\LdapUsers->Piwik\Plugins\LoginLdap\Model\{closure}(Object(Piwik\Plugins\LoginLdap\Model\LdapUsers), Object(Piwik\Plugins\LoginLdap\Ldap\Client), Object(Piwik\Plugins\LoginLdap\Ldap\ServerInfo))
  #2 /data/www/piwik/htdocs/plugins/LoginLdap/Model/LdapUsers.php(248): Piwik\Plugins\LoginLdap\Model\LdapUsers->doWithClient(Object(Closure))
  #3 /data/www/piwik/htdocs/plugins/LoginLdap/Model/LdapUsers.php(165): Piwik\Plugins\LoginLdap\Model\LdapUsers->getUser('$USERNAME...', Object(Piwik\Plugins\LoginLdap\Ldap\Client))
  #4 /data/www/piwik/htdocs/plugins/LoginLdap/Model/LdapUsers.php(506): Piwik\Plugins\LoginLdap\Model\LdapUsers->Piwik\Plugins\LoginLdap\Model\{closure}(Object(Piwik\Plugins\LoginLdap\Model\LdapUsers), Object(Piwik\Plugins\LoginLdap\Ldap\Client), Object(Piwik\Plugins\LoginLdap\Ldap\ServerInfo))
  #5 /data/www/piwik/htdocs/plugins/LoginLdap/Model/LdapUsers.php(201): Piwik\Plugins\LoginLdap\Model\LdapUsers->doWithClient(Object(Closure))
  #6 /data/www/piwik/htdocs/plugins/LoginLdap/Auth/Base.php(341): Piwik\Plugins\LoginLdap\Model\LdapUsers->authenticate('$USERNAME...', '$PASSWORD')
  #7 /data/www/piwik/htdocs/plugins/LoginLdap/Auth/LdapAuth.php(103): Piwik\Plugins\LoginLdap\Auth\Base->authenticateByLdap()
  #8 /data/www/piwik/htdocs/plugins/Login/SessionInitializer.php(162): Piwik\Plugins\LoginLdap\Auth\LdapAuth->authenticate()
  #9 /data/www/piwik/htdocs/plugins/Login/SessionInitializer.php(114): Piwik\Plugins\Login\SessionInitializer->doAuthenticateSession(Object(Piwik\Plugins\LoginLdap\Auth\LdapAuth))
  #10 /data/www/piwik/htdocs/plugins/Login/Controller.php(204): Piwik\Plugins\Login\SessionInitializer->initSession(Object(Piwik\Plugins\LoginLdap\Auth\LdapAuth), false)
  #11 /data/www/piwik/htdocs/plugins/Login/Controller.php(103): Piwik\Plugins\Login\Controller->authenticateAndRedirect('$USERNAME...', '$PASSWORD', false)
  #12 /data/www/piwik/htdocs/plugins/Login/Controller.php(81): Piwik\Plugins\Login\Controller->login()
  #13 [internal function]: Piwik\Plugins\Login\Controller->index()

Can someone help me please ??

Cheers,

- Pascal

**Comment by denbekker** [comment]
ok we found the mistake.. changed the filter and added ldaps:// to the server url.. no everything is working.. :-)
