### ISSUE TITLE
LoginLdap plugin is broken after updating RDS CA cert

### ISSUE THREAD

**Issue by tejochan** [piwik/plugin-LoginLdap#379]
LDAP connectivity is lost after changes to AWS RDS CA. I've the cert configured in the docker image and I updated and deployed the changes.
I've verified the LDAP connection is working from the Matomo Container. 
PHP  - 8.3
MySQL - 8.0.35
LoginLdap - 4.5.5

Please advice.

LOG>>

```
:/usr/share/nginx/html# php ./console loginldap:synchronize-users
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20230831/pdo_mysql (/usr/lib/php/20230831/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20230831/pdo_mysql.so (/usr/lib/php/20230831/pdo_mysql.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Deprecated:  Function utf8_encode() is deprecated in /usr/share/nginx/html/vendor/szymach/c-pchart/constants.php on line 48
WARNING [2024-08-23 21:17:47] 515  /usr/share/nginx/html/plugins/PrivacyManager/DoNotTrackHeaderChecker.php(29): Deprecated - Creation of dynamic property Piwik\Plugins\PrivacyManager\DoNotTrackHeaderChecker::$config is deprecated - Matomo 4.12.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
WARNING [2024-08-23 21:17:47] 515  /usr/share/nginx/html/core/Plugin.php(163): Deprecated - Calling get_class() without arguments is deprecated - Matomo 4.12.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
ERROR [2024-08-23 21:17:47] 515  Uncaught exception: Error: Undefined constant PDO::MYSQL_ATTR_SSL_CA in /usr/share/nginx/html/core/Db/Adapter/Pdo/Mysql.php:50
Stack trace:
#0 /usr/share/nginx/html/core/Db/Adapter.php(49): Piwik\Db\Adapter\Pdo\Mysql->__construct()
#1 /usr/share/nginx/html/core/Db.php(157): Piwik\Db\Adapter::factory()
#2 /usr/share/nginx/html/core/Db.php(56): Piwik\Db::createDatabaseObject()
#3 /usr/share/nginx/html/core/Db.php(302): Piwik\Db::get()
#4 /usr/share/nginx/html/core/Option.php(288): Piwik\Db::fetchAll()
#5 /usr/share/nginx/html/core/Option.php(178): Piwik\Option->autoload()
#6 /usr/share/nginx/html/core/Option.php(48): Piwik\Option->getValue()
#7 /usr/share/nginx/html/plugins/UserCountry/LocationProvider.php(341): Piwik\Option::get()
#8 /usr/share/nginx/html/plugins/UserCountry/LocationProvider.php(357): Piwik\Plugins\UserCountry\LocationProvider::getCurrentProviderId()
#9 /usr/share/nginx/html/plugins/GeoIp2/Commands/ConvertRegionCodesToIso.php(34): Piwik\Plugins\UserCountry\LocationProvider::getCurrentProvider()
#10 /usr/share/nginx/html/vendor/symfony/console/Symfony/Component/Console/Application.php(388): Piwik\Plugins\GeoIp2\Commands\ConvertRegionCodesToIso->isEnabled()
#11 /usr/share/nginx/html/core/Console.php(163): Symfony\Component\Console\Application->add()
#12 /usr/share/nginx/html/core/Console.php(121): Piwik\Console->addCommandIfExists()
#13 /usr/share/nginx/html/core/Console.php(87): Piwik\Console->doRunImpl()
#14 /usr/share/nginx/html/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun()
#15 /usr/share/nginx/html/console(32): Symfony\Component\Console\Application->run()
#16 {main}
Uncaught exception in /usr/share/nginx/html/core/Db/Adapter/Pdo/Mysql.php line 50:
Undefined constant PDO::MYSQL_ATTR_SSL_CA

```

**Comment by snake14** [comment]
Hi @tejochan . I'm sorry to hear that you're experiencing this issue. Judging by the error, it looks like your deployment isn't quite right. It's acting like the PHP MySQL module isn't installed. This link on SO, might provide some useful information: https://stackoverflow.com/questions/32728860/php-7-rc3-how-to-install-missing-mysql-pdo

**Comment by tejochan** [comment]
I verified the PHP MySQL is installed. PDO is installed. 
```
root@xxxxxxxx/usr/share/nginx/html# php -i | grep PDO
PDO
PDO support => enabled
PDO drivers => mysql
PDO Driver for MySQL => enabled
```

**Comment by snake14** [comment]
Hi @tejochan . Can you please try `grep pdo_mysql`, as everything is pointing to the `pdo_mysql` extension not being installed/enabled? The warning in the log output you originally shared indicates this as well:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20230831/pdo_mysql (/usr/lib/php/20230831/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20230831/pdo_mysql.so (/usr/lib/php/20230831/pdo_mysql.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by tejochan** [comment]
PHP version used for the application and version I ran with were different. 
PHP 8.1 is used for matomo. 

Seeing `Could not bind as LDAP admin` error. I verified the LDAP URL is active and LDAP Bind Username and Password are active. Other apps running on the same platform are able to make LDAP connection.

```
root@xxxxxx-1870-4855-7346-5788:/usr/share/nginx/html# ./console loginldap:synchronize-users
WARNING [2024-08-28 14:34:09] 457  /usr/share/nginx/html/plugins/LoginLdap/Ldap/Client.php(96): Warning - ldap_bind(): Unable to bind to server: Can't contact LDAP server - Matomo 4.12.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
INFO [2024-08-28 14:34:09] 457  LdapUsers::makeLdapClient: Using LDAP server ldaps://LDAPURL.domain.io:636:636
WARNING [2024-08-28 14:34:09] 457  /usr/share/nginx/html/plugins/LoginLdap/Ldap/Client.php(153): Warning - ldap_bind(): Unable to bind to server: Can't contact LDAP server - Matomo 4.12.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
ERROR [2024-08-28 14:34:09] 457  Uncaught exception: /usr/share/nginx/html/plugins/LoginLdap/Model/LdapUsers.php(591): Could not bind as LDAP admin. [Query: , CLI mode: 1]



  [Exception]
  Could not bind as LDAP admin.
```

**Comment by tejochan** [comment]
also checked if I can connect to LDAP from the machine
```
# openssl s_client -showcerts -servername LDAPURL.domain.io -connect LDAPURL.domain.io:636
CONNECTED(00000003)
```

**Comment by snake14** [comment]
Hi @tejochan . Looking in the warning message, it appears that the port is being specified twice:
```
Using LDAP server ldaps://LDAPURL.domain.io:636:636
```
Are you including the port as part of the Server URL (host)? If so, please remove it as there is a separate port field.

**Comment by tejochan** [comment]
yeah, I tried removing it and ran too

```
root@xxx-1870-xxxx-7346-5788:/usr/share/nginx/html# ./console loginldap:synchronize-users --login=ldaps://LDAPURL.domain.io -vvv
DEBUG [2024-08-28 21:40:11] 8034  UserSynchronizer::makeConfigured(): Using UserAccessMapper when synchronizing users.
DEBUG [2024-08-28 21:40:11] 8034  UserSynchronizer::makeConfigured: configuring with defaultSitesWithViewAccess =
DEBUG [2024-08-28 21:40:11] 8034  UserSynchronizer::makeConfigured(): Using UserAccessMapper when synchronizing users.
DEBUG [2024-08-28 21:40:11] 8034  UserSynchronizer::makeConfigured: configuring with defaultSitesWithViewAccess =
Synchronizing 'ldaps://LDAPURL.domain.io'...  DEBUG [2024-08-28 21:40:11] 8034  Model\LdapUsers: start getUser() with array["ldaps://LDAPURL.domain.io"]
DEBUG [2024-08-28 21:40:11] 8034  Calling ldap_connect('ldaps://10.XX.1.XXX:636', 389)
DEBUG [2024-08-28 21:40:11] 8034  ldap_connect result is [object LDAP\Connection]
WARNING [2024-08-28 21:40:26] 8034  /usr/share/nginx/html/plugins/LoginLdap/Ldap/Client.php(96): Warning - ldap_bind(): Unable to bind to server: Can't contact LDAP server - Matomo 4.12.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
DEBUG [2024-08-28 21:40:26] 8034  anonymous ldap_bind call finished; connection ok
INFO [2024-08-28 21:40:26] 8034  LdapUsers::makeLdapClient: Using LDAP server ldaps://10.XX.1.XXX:636:389
DEBUG [2024-08-28 21:40:26] 8034  Calling ldap_bind([object LDAP\Connection], 'CN=s-ldapbindMatomoNew,OU=Service,OU=Accounts,OU=XXX,OU=XX,DC=domain,DC=io', <password[length=22]>)
WARNING [2024-08-28 21:40:41] 8034  /usr/share/nginx/html/plugins/LoginLdap/Ldap/Client.php(153): Warning - ldap_bind(): Unable to bind to server: Can't contact LDAP server - Matomo 4.12.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
DEBUG [2024-08-28 21:40:41] 8034  ldap_bind result is '0'
DEBUG [2024-08-28 21:40:41] 8034  Calling ldap_close([object LDAP\Connection])
DEBUG [2024-08-28 21:40:41] 8034  ldap_close returned true
failed!

Synchronized 0 users!

Could not synchronize the following users in LDAP:
ldaps://LDAPURL.domain.io		Could not bind as LDAP admin.
```

**Comment by snake14** [comment]
@tejochan I'm not sure why it would be doing that. The `Unable to bind to server: Can't contact LDAP server` error usually indicates a communication issue or a misconfigured certificate.

Any suggestions @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@tejochan Can you check if this command works from your box with/without sudo depending on your setup
```
sudo ldapsearch -x -H "ldap://{hostname}:{port}" -b "dc={base_dn}" -D "{admin_user}" -W
// If ssl
sudo ldapsearch -x -H "ldaps://{hostname}:{port}" -b "dc={base_dn}" -D "{admin_user}" -W
```

Also seeing your debug command
```
 Calling ldap_connect('ldaps://10.XX.1.XXX:636', 389)
 ```
 
 Seems like you are passing port in the host too which should be separate, please check your `config/config.ini.php` if the configs are saved correctly or not for `LoginLdap_*`

**Comment by tejochan** [comment]
this is resolved. Nothing wrong with the plugin or Matomo config. 
I had to update a dependency for ubuntu for LDAP i.e.` ibldap-common`
https://github.com/docker-library/php/issues/1194
